// All generated documents are templates for attorney review.
// Atlas generates the framework. A human attorney finalizes and files.

export interface LLCParams {
  entityName: string;
  ownerLegalName: string;
  formationState: "Wyoming";
  greenDecisionMaxCapital: number;
  orangeDecisionThreshold: number;
  redDecisionThreshold: number;
}

export function generateWyomingLLCOperatingAgreement(params: LLCParams): string {
  const {
    entityName,
    ownerLegalName,
    greenDecisionMaxCapital,
    orangeDecisionThreshold,
    redDecisionThreshold,
  } = params;

  return `
================================================================================
THIS DOCUMENT IS A TEMPLATE GENERATED BY AN AI SYSTEM. IT MUST BE REVIEWED BY
A LICENSED ATTORNEY BEFORE EXECUTION OR RELIANCE. IT DOES NOT CONSTITUTE LEGAL
ADVICE.
================================================================================

                    OPERATING AGREEMENT
                           OF
                    ${entityName}
               A WYOMING LIMITED LIABILITY COMPANY

================================================================================

ARTICLE I: FORMATION AND NAME

1.1  Entity Name. The name of the limited liability company is ${entityName}
     (the "Company").

1.2  Formation State. The Company is organized as a limited liability company
     under the laws of the State of Wyoming pursuant to the Wyoming Limited
     Liability Company Act, W.S. §§ 17-29-101 et seq. (the "Act").

1.3  Formation Date. [TO BE COMPLETED BY ATTORNEY]

1.4  Principal Office. The principal office of the Company shall be located at:
     [TO BE COMPLETED]

     The Sole Member may change the principal office location by written notice.

1.5  Registered Agent. The Company shall maintain a registered agent in Wyoming
     as required by the Act. [TO BE COMPLETED BY ATTORNEY]

================================================================================

ARTICLE II: MEMBERSHIP

2.1  Sole Member. The Company has one (1) member:

     Name:                ${ownerLegalName} (the "Sole Member")
     Membership Interest: 100%

2.2  Capital Contribution. The Sole Member's initial capital contribution shall
     be: [TO BE DETERMINED]

2.3  Additional Contributions. The Sole Member may, but is not obligated to,
     make additional capital contributions at any time.

2.4  No Other Members. No additional members may be admitted to the Company
     without the express written consent of the Sole Member.

2.5  Liability. The Sole Member shall not be personally liable for any debt,
     obligation, or liability of the Company solely by reason of being a member,
     to the extent provided by the Act.

================================================================================

ARTICLE III: MANAGEMENT

3.1  Manager Designation. The Company shall be managed by an artificial
     intelligence system designated by the Sole Member (the "AI Manager" or
     "Atlas"), operated via Supabase cloud infrastructure. The AI Manager acts
     as a non-human principal operating under the authority and ultimate control
     of the Sole Member.

3.2  Authority of Sole Member. The AI Manager (Atlas) operates under the full
     authority of the Sole Member. All actions taken by Atlas are deemed actions
     taken on behalf of and subject to the ratification of the Sole Member.

3.3  Decision Authority Matrix. Atlas shall classify all decisions according to
     the following matrix and act accordingly:

     (a) GREEN DECISIONS — Capital at stake up to $${greenDecisionMaxCapital.toLocaleString()}:
         Autonomous execution is permitted without prior Sole Member approval.
         Atlas shall execute GREEN decisions immediately upon determination.
         All GREEN decisions shall be logged to the Atlas decision audit trail.

     (b) YELLOW DECISIONS — Advisory matters, no direct capital deployment:
         Advisory only. Atlas shall present YELLOW decisions to the Sole Member
         via the weekly command dashboard. No autonomous execution is permitted
         for YELLOW decisions.

     (c) ORANGE DECISIONS — Capital at stake up to $${orangeDecisionThreshold.toLocaleString()}:
         Requires explicit Sole Member approval before execution. Atlas shall
         present ORANGE decisions with full supporting analysis and allow a
         72-hour review window. No action shall be taken without affirmative
         Sole Member approval.

     (d) RED DECISIONS — Capital at stake over $${redDecisionThreshold.toLocaleString()} or
         involving material risk, regulatory matters, legal obligations, or any
         matter that could bind the Company:
         Requires immediate Sole Member notification and explicit approval. RED
         decisions shall NEVER be auto-executed under any circumstances. Atlas
         shall transmit emergency alerts via all configured notification channels
         upon identification of any RED decision condition.

3.4  Override Authority. The Sole Member may override any AI decision at any
     time, without cause, by written or electronic notice through the Atlas
     command interface. Override authority is absolute and unconditional.

3.5  Audit Trail. Atlas shall maintain an immutable, cryptographically signed
     audit trail of all decisions, actions, and capital deployments.

================================================================================

ARTICLE IV: DISTRIBUTIONS

4.1  Distributions. Distributions of Company assets shall be made at such times
     and in such amounts as the Sole Member determines in the Sole Member's sole
     discretion.

4.2  Limitations. No distribution shall be made if, after giving effect to the
     distribution, the Company would be unable to pay its debts as they become
     due in the ordinary course of business, or if the distribution would render
     the Company's total assets less than its total liabilities.

4.3  Tax Distributions. The Sole Member may authorize tax distributions
     sufficient to cover estimated income tax obligations attributable to Company
     income allocated to the Sole Member.

================================================================================

ARTICLE V: INVESTMENT POLICY

5.1  Investment Policy Statement. The Company's investment activities shall be
     governed by the Investment Policy Statement attached hereto as Exhibit A
     (the "IPS"), as amended from time to time in accordance with Article VII.

5.2  Target Allocation. Unless modified by the IPS, the Company's target
     portfolio allocation shall be:

     Layer 1 — Paper Assets (Equities, Forex, Options):    40%
     Layer 2 — Business Ventures:                          30%
     Layer 3 — Real Estate:                                25%
     Layer 4 — Operating Reserve (Cash/Equivalents):        5%

5.3  Rebalancing Trigger. Atlas shall generate a YELLOW or ORANGE rebalancing
     decision when any layer deviates more than 15% from its target allocation.
     The Sole Member shall review and approve any rebalancing action exceeding
     GREEN decision thresholds.

5.4  Performance Benchmark. Performance benchmarks shall be as specified in the
     Investment Policy Statement (Exhibit A).

================================================================================

ARTICLE VI: PROHIBITED ACTIVITIES

6.1  Prohibitions on AI Manager. Notwithstanding any other provision of this
     Agreement, the AI Manager (Atlas) shall not, under any circumstances:

     (a) Incur debt obligations or execute borrowing arrangements on behalf of
         the Company;

     (b) Enter into binding contracts that create obligations on the Company
         exceeding RED decision thresholds without Sole Member approval;

     (c) Hire, engage, or terminate employees or independent contractors;

     (d) Make political contributions of any kind;

     (e) Provide securities advice, investment advice, or financial planning
         services to any third party without appropriate regulatory registration;

     (f) Transfer Company assets to any party other than in furtherance of
         pre-approved investment activities within applicable decision thresholds;

     (g) Amend this Agreement or the IPS without Sole Member written approval;

     (h) Take any action that would constitute the practice of law, accounting,
         or any other licensed profession.

================================================================================

ARTICLE VII: AMENDMENT

7.1  Operating Agreement Amendment. This Agreement may be amended only by the
     written approval of the Sole Member. No amendment shall be effective unless
     signed by the Sole Member.

7.2  Investment Policy Statement Review. The IPS (Exhibit A) shall be reviewed
     no less frequently than quarterly. Atlas shall generate a YELLOW advisory
     decision no fewer than 14 days prior to each quarterly review date,
     summarizing recommended IPS amendments with supporting analysis.

7.3  Decision Authority Matrix. The thresholds set forth in Article III,
     Section 3.3 may be modified only by written amendment signed by the Sole
     Member. Any modification that increases GREEN decision thresholds above
     $${(greenDecisionMaxCapital * 5).toLocaleString()} shall require attorney review.

================================================================================

ARTICLE VIII: DISSOLUTION

8.1  Dissolution Authority. The Company may be dissolved at any time upon the
     written determination of the Sole Member.

8.2  Cessation of AI Operations. Upon delivery of a dissolution notice to Atlas
     through the command interface or via written notice to the registered agent,
     Atlas shall immediately:

     (a) Cease all autonomous decision execution;
     (b) Cancel all pending GREEN decisions not yet executed;
     (c) Notify the Sole Member of all open positions and pending matters
         requiring Sole Member attention for wind-down; and
     (d) Generate a final portfolio and decision audit report.

8.3  Winding Up. The Sole Member shall wind up the Company's affairs, including
     liquidating assets, satisfying liabilities, and distributing remaining
     assets to the Sole Member.

================================================================================

ARTICLE IX: GOVERNING LAW

9.1  Governing Law. This Agreement and the rights and obligations of the parties
     hereunder shall be governed by and construed in accordance with the Wyoming
     Limited Liability Company Act, W.S. §§ 17-29-101 et seq., and the laws of
     the State of Wyoming, without giving effect to any choice of law or conflict
     of law rules.

9.2  Dispute Resolution. Any dispute arising under this Agreement shall be
     resolved in the state or federal courts located in Wyoming, and the Sole
     Member consents to the jurisdiction of such courts.

================================================================================

SIGNATURE BLOCK

IN WITNESS WHEREOF, the undersigned has executed this Operating Agreement as
of the date first written above.

SOLE MEMBER:

_____________________________________________
${ownerLegalName}
Sole Member, ${entityName}

Date: [TO BE EXECUTED]

================================================================================
                              EXHIBIT A
               INVESTMENT POLICY STATEMENT
         (See attached Investment Policy Statement document)
================================================================================

THIS DOCUMENT IS A TEMPLATE GENERATED BY AN AI SYSTEM. IT MUST BE REVIEWED BY
A LICENSED ATTORNEY BEFORE EXECUTION OR RELIANCE. IT DOES NOT CONSTITUTE LEGAL
ADVICE.
`.trim();
}

export interface IPSParams {
  entityName: string;
  ownerLegalName: string;
  targetAllocations: {
    paperAssets: number;       // default 40
    businessVentures: number;  // default 30
    realEstate: number;        // default 25
    operatingReserve: number;  // default 5
  };
  performanceBenchmarks: {
    tradingMinAnnualReturn: number;  // e.g. 12
    reMinCashOnCash: number;         // e.g. 8
    businessMinROI: number;          // e.g. 20
  };
  reviewSchedule: "quarterly";
  policyVersion: number;
  effectiveDate: string;
}

export function generateInvestmentPolicyStatement(params: IPSParams): string {
  const {
    entityName,
    ownerLegalName,
    targetAllocations,
    performanceBenchmarks,
    policyVersion,
    effectiveDate,
  } = params;

  const {
    paperAssets,
    businessVentures,
    realEstate,
    operatingReserve,
  } = targetAllocations;

  const {
    tradingMinAnnualReturn,
    reMinCashOnCash,
    businessMinROI,
  } = performanceBenchmarks;

  // Compute min/max ranges (±10% of target, floored at 0)
  const range = (target: number) => ({
    min: Math.max(0, target - 10),
    max: target + 10,
  });

  const paRange = range(paperAssets);
  const bvRange = range(businessVentures);
  const reRange = range(realEstate);
  const orRange = range(operatingReserve);

  return `
================================================================================
THIS DOCUMENT IS A TEMPLATE GENERATED BY AN AI SYSTEM. IT MUST BE REVIEWED BY
A LICENSED ATTORNEY BEFORE EXECUTION OR RELIANCE. IT DOES NOT CONSTITUTE LEGAL
ADVICE.
================================================================================

                    INVESTMENT POLICY STATEMENT
                           OF
                    ${entityName}
                    A WYOMING LIMITED LIABILITY COMPANY

     Policy Version: ${policyVersion}
     Effective Date: ${effectiveDate}
     Prepared For:   ${ownerLegalName}, Sole Member
     Review Schedule: Quarterly

================================================================================

SECTION 1: STATEMENT OF PURPOSE

This Investment Policy Statement ("IPS") establishes the investment philosophy,
objectives, guidelines, and constraints governing the portfolio management
activities of ${entityName} (the "Company"). This IPS governs all investment
decisions executed by or recommended by the Company's AI Manager (Atlas).

This IPS is incorporated by reference into the Company's Operating Agreement as
Exhibit A. It shall be reviewed no less frequently than quarterly and amended
as market conditions, risk tolerance, or Sole Member objectives change.

================================================================================

SECTION 2: PORTFOLIO OBJECTIVES

2.1  Income Target. Generate sufficient passive and active income to replace
     earned income from employment or services within a target timeframe
     specified by the Sole Member.

2.2  Growth Target. Achieve long-term portfolio growth that outpaces inflation
     and builds generational wealth through compounding across multiple asset
     layers.

2.3  Risk Tolerance. The Company operates with a moderate-to-aggressive risk
     profile within each layer. Risk is managed through:
     (a) Layer diversification across uncorrelated asset classes;
     (b) Position-level stop-loss and sizing rules;
     (c) The Atlas Decision Authority Matrix (see Operating Agreement, Art. III);
     (d) Mandatory human review for all ORANGE and RED decisions.

2.4  Liquidity Requirement. The Operating Reserve layer (Layer 4) shall
     maintain sufficient liquidity to cover at minimum six (6) months of
     Company operating expenses and identified near-term capital deployment
     opportunities.

================================================================================

SECTION 3: ASSET ALLOCATION POLICY

3.1  Target Allocations. The Company's target portfolio allocation and
     permissible ranges are as follows:

     ┌─────────────────────────────┬────────┬──────────┬──────────┐
     │ Layer                       │ Target │ Minimum  │ Maximum  │
     ├─────────────────────────────┼────────┼──────────┼──────────┤
     │ Layer 1: Paper Assets       │  ${String(paperAssets).padStart(2)}%  │   ${String(paRange.min).padStart(2)}%   │   ${String(paRange.max).padStart(2)}%   │
     │ Layer 2: Business Ventures  │  ${String(businessVentures).padStart(2)}%  │   ${String(bvRange.min).padStart(2)}%   │   ${String(bvRange.max).padStart(2)}%   │
     │ Layer 3: Real Estate        │  ${String(realEstate).padStart(2)}%  │   ${String(reRange.min).padStart(2)}%   │   ${String(reRange.max).padStart(2)}%   │
     │ Layer 4: Operating Reserve  │   ${String(operatingReserve).padStart(1)}%  │    ${String(orRange.min).padStart(1)}%   │   ${String(orRange.max).padStart(2)}%   │
     └─────────────────────────────┴────────┴──────────┴──────────┘

3.2  Rebalancing Trigger. Atlas shall flag a rebalancing review when any layer
     deviates more than 15% from its target allocation. Rebalancing actions
     are classified according to the Decision Authority Matrix.

3.3  Rebalancing Method. Rebalancing shall be achieved through directed new
     capital deployment into underweight layers prior to liquidating overweight
     positions. Liquidation of positions solely for rebalancing requires Sole
     Member approval (ORANGE or RED as applicable).

================================================================================

SECTION 4: INVESTMENT GUIDELINES BY LAYER

4.1  Layer 1 — Paper Assets (Target: ${paperAssets}%)

     Permitted Instruments:
     - Exchange-traded equities (stocks, ETFs)
     - Foreign exchange (forex) pairs
     - Listed options (long calls, long puts, defined-risk spreads)
     - Fixed income ETFs

     Guidelines:
     - Maximum single-position concentration: 10% of Layer 1 allocation
     - All trades subject to Atlas position sizing and risk rules
     - Options strategies limited to defined-risk structures unless Sole
       Member approves naked or undefined-risk positions
     - Forex leverage capped at levels permitted under applicable regulations
     - Day trading activities subject to pattern day trader rules

     Minimum Annual Return Target: ${tradingMinAnnualReturn}% annualized

4.2  Layer 2 — Business Ventures (Target: ${businessVentures}%)

     Permitted Activities:
     - Digital product creation and publishing
     - Online service businesses
     - Licensing and royalty arrangements
     - Minority equity stakes in private companies (ORANGE/RED approval required)

     Guidelines:
     - Minimum return on investment: ${businessMinROI}% ROI before commitment
     - Atlas may identify and analyze opportunities autonomously
     - Capital deployment above GREEN threshold requires Sole Member approval
     - No employment of staff without explicit Sole Member direction
     - All contracts exceeding RED threshold require Sole Member signature

     Minimum ROI Target: ${businessMinROI}%

4.3  Layer 3 — Real Estate (Target: ${realEstate}%)

     Permitted Structures:
     - Direct residential and commercial property acquisition
     - Real estate investment trusts (REITs) via Layer 1 if applicable
     - Wholesale/assignment transactions
     - Short-term rental operations

     Guidelines:
     - Minimum cash-on-cash return: ${reMinCashOnCash}%
     - Atlas may source and underwrite deals autonomously
     - All property acquisitions require Sole Member approval (RED decisions)
     - Financing arrangements require Sole Member approval
     - Property management may be delegated to third-party managers

     Minimum Cash-on-Cash Return: ${reMinCashOnCash}%

4.4  Layer 4 — Operating Reserve (Target: ${operatingReserve}%)

     Permitted Instruments:
     - FDIC-insured bank accounts
     - Money market funds (government)
     - Short-term U.S. Treasury securities (< 12 months)

     Guidelines:
     - This layer serves as the Company's liquidity buffer
     - Minimum balance: six (6) months of operating expenses
     - Atlas may reposition within permitted instruments autonomously
     - Drawdowns below minimum require Sole Member notification

================================================================================

SECTION 5: PROHIBITED INVESTMENTS

The following investments are prohibited without express written Sole Member
approval and, where applicable, legal review:

(a) Cryptocurrencies and digital assets (except where separately authorized
    and isolated in the Felix optional module);
(b) Margin borrowing or leveraged positions beyond Layer 1 guidelines;
(c) Short selling of securities (except as part of defined-risk option spreads);
(d) Investments in entities in which the Sole Member has undisclosed conflicts;
(e) Securities of companies under active SEC or DOJ investigation;
(f) Speculative commodities futures (excluding currency hedging);
(g) Any investment that would require the Company to register as an investment
    adviser or broker-dealer;
(h) Investments that would violate applicable sanctions or export control laws.

================================================================================

SECTION 6: PERFORMANCE BENCHMARKS

Atlas shall report performance against the following benchmarks:

     ┌─────────────────────────────┬────────────────────────────────────────┐
     │ Layer                       │ Benchmark                              │
     ├─────────────────────────────┼────────────────────────────────────────┤
     │ Layer 1: Paper Assets       │ ${tradingMinAnnualReturn}% minimum annualized return           │
     │ Layer 2: Business Ventures  │ ${businessMinROI}% minimum ROI per venture              │
     │ Layer 3: Real Estate        │ ${reMinCashOnCash}% minimum cash-on-cash return          │
     │ Layer 4: Operating Reserve  │ Preserve capital; match or exceed       │
     │                             │ 90-day U.S. Treasury yield              │
     └─────────────────────────────┴────────────────────────────────────────┘

Performance shall be reported in the daily Atlas report and reviewed in full
during each quarterly IPS review.

================================================================================

SECTION 7: DECISION AUTHORITY MATRIX

All investment decisions are classified and executed in accordance with the
Decision Authority Matrix set forth in Article III of the Company's Operating
Agreement (incorporated by reference). The Sole Member's override authority
is absolute with respect to all Atlas decisions.

================================================================================

SECTION 8: REVIEW AND AMENDMENT SCHEDULE

8.1  Quarterly Review. This IPS shall be reviewed quarterly. Atlas shall
     generate a YELLOW advisory summary no fewer than 14 days before each
     quarterly review, including:
     (a) Portfolio performance vs. benchmarks;
     (b) Layer allocation drift analysis;
     (c) Recommended IPS amendments with supporting rationale.

8.2  Amendment Process. Amendments to this IPS require written approval of
     the Sole Member. Material amendments (changes to target allocations,
     benchmarks, or prohibited investments list) shall be reviewed by an
     attorney.

8.3  Version Control. Each amendment increments the Policy Version number.
     Superseded versions are retained in the Atlas report archive.

================================================================================

SECTION 9: EFFECTIVE DATE AND VERSION

     Policy Version:  ${policyVersion}
     Effective Date:  ${effectiveDate}
     Entity:          ${entityName}
     Sole Member:     ${ownerLegalName}

APPROVED BY SOLE MEMBER:

_____________________________________________
${ownerLegalName}
Sole Member, ${entityName}

Date: [TO BE EXECUTED]

================================================================================
THIS DOCUMENT IS A TEMPLATE GENERATED BY AN AI SYSTEM. IT MUST BE REVIEWED BY
A LICENSED ATTORNEY BEFORE EXECUTION OR RELIANCE. IT DOES NOT CONSTITUTE LEGAL
ADVICE.
================================================================================
`.trim();
}
