-- ============================================================
-- Atlas Deprecation Log — 43 functions consolidated into 7
-- Records every function absorbed into the new Atlas architecture
-- ============================================================

CREATE TABLE IF NOT EXISTS public.deprecation_log (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  deprecated_name text NOT NULL,
  deprecated_at timestamptz DEFAULT now(),
  reason text NOT NULL,
  absorbed_into text NOT NULL,
  original_actions text[],
  notes text
);

-- ─── atlas-core (10 functions) ────────────────────────────────────────────────

INSERT INTO public.deprecation_log (deprecated_name, reason, absorbed_into, original_actions, notes) VALUES
(
  'forge_chat',
  'Consolidated into unified atlas-core orchestration layer',
  'atlas-core',
  ARRAY['CHAT', 'RESPOND', 'CONVERSE'],
  'Core conversation handling folded into atlas-core runtime'
),
(
  'forge_execute',
  'Consolidated into unified atlas-core orchestration layer',
  'atlas-core',
  ARRAY['EXECUTE', 'RUN_TASK', 'DISPATCH'],
  'Task execution folded into atlas-core action dispatcher'
),
(
  'forge_compress',
  'Consolidated into unified atlas-core orchestration layer',
  'atlas-core',
  ARRAY['COMPRESS', 'SUMMARIZE_MEMORY', 'COMPACT'],
  'Memory compression now handled internally by atlas-core memory manager'
),
(
  'forge_learn',
  'Consolidated into unified atlas-core orchestration layer',
  'atlas-core',
  ARRAY['LEARN', 'INGEST', 'UPDATE_KNOWLEDGE'],
  'Learning pipeline merged into atlas-core dossier writer'
),
(
  'forge_suggest',
  'Consolidated into unified atlas-core orchestration layer',
  'atlas-core',
  ARRAY['SUGGEST', 'RECOMMEND', 'PROPOSE'],
  'Suggestion engine absorbed into atlas-core decision system'
),
(
  'atlas_autonomous_loop',
  'Replaced by structured 7-function architecture with explicit cron scheduling',
  'atlas-core',
  ARRAY['AUTONOMOUS_TICK', 'LOOP', 'SELF_DRIVE'],
  'Loop logic distributed across atlas-signal morning brief and atlas-core noon check'
),
(
  'atlas_embed',
  'Embedding now handled internally by atlas-core memory module',
  'atlas-core',
  ARRAY['EMBED', 'VECTORIZE', 'ENCODE_MEMORY'],
  'pgvector embedding calls abstracted behind atlas_memory table inserts'
),
(
  'atlas_self_eval',
  'Self-evaluation merged into atlas-core continuous improvement cycle',
  'atlas-core',
  ARRAY['SELF_EVAL', 'EVALUATE_PERFORMANCE', 'SCORE_SELF'],
  'Evaluation now runs as part of atlas-core weekly digest'
),
(
  'atlas_noon_check',
  'Mid-day check folded into atlas-core orchestration heartbeat',
  'atlas-core',
  ARRAY['NOON_CHECK', 'MID_DAY_REVIEW'],
  'Noon check logic absorbed into atlas-core cron-driven monitoring'
),
(
  'atlas_reengagement',
  'Multi-operator concept deprecated; single-operator architecture adopted',
  'atlas-core',
  ARRAY['REENGAGE', 'REACTIVATE_OPERATOR', 'MULTI_OPERATOR_PING'],
  'DEPRECATED: old multi-operator concept. Single-operator model does not require re-engagement logic'
);

-- ─── atlas-trade (13 functions) ───────────────────────────────────────────────

INSERT INTO public.deprecation_log (deprecated_name, reason, absorbed_into, original_actions, notes) VALUES
(
  'atlas_execute_trade',
  'Trade execution consolidated into atlas-trade with GREEN/YELLOW/ORANGE/RED decision gate',
  'atlas-trade',
  ARRAY['EXECUTE_TRADE', 'PLACE_ORDER', 'SUBMIT_TRADE'],
  'All trade execution now routes through atlas_decision_queue before broker submission'
),
(
  'atlas_forex_scan',
  'Forex scanning merged into unified atlas-trade opportunity scanner',
  'atlas-trade',
  ARRAY['FOREX_SCAN', 'SCAN_FX', 'FX_OPPORTUNITY'],
  'Forex pairs now covered under atlas-trade opportunity_scan action'
),
(
  'atlas_risk_check',
  'Risk check consolidated into atlas-trade pre-execution gate',
  'atlas-trade',
  ARRAY['RISK_CHECK', 'CHECK_RISK', 'VALIDATE_RISK'],
  'Risk validation now embedded in atlas-trade GREEN/RED decision logic'
),
(
  'atlas_market_brief',
  'Market brief rolled into atlas-trade daily signal output',
  'atlas-trade',
  ARRAY['MARKET_BRIEF', 'MARKET_SUMMARY', 'DAILY_BRIEF'],
  'Market briefings now generated by atlas-signal and consumed by atlas-trade'
),
(
  'atlas_trade_thesis',
  'Trade thesis generation absorbed into atlas-trade recommendation engine',
  'atlas-trade',
  ARRAY['TRADE_THESIS', 'BUILD_THESIS', 'GENERATE_THESIS'],
  'Thesis construction now part of atlas-trade signal-to-decision pipeline'
),
(
  'atlas_watchlist_patrol',
  'Watchlist monitoring merged into atlas-trade real-time opportunity scanner',
  'atlas-trade',
  ARRAY['WATCHLIST_PATROL', 'PATROL_WATCHLIST', 'MONITOR_WATCHLIST'],
  'Watchlist alerts now surface through atlas_decision_queue as YELLOW decisions'
),
(
  'atlas_options_scan',
  'Options scanning consolidated into atlas-trade opportunity scanner',
  'atlas-trade',
  ARRAY['OPTIONS_SCAN', 'SCAN_OPTIONS', 'FIND_OPTIONS'],
  'Options flow and unusual activity now tracked under atlas-trade opportunity_scan'
),
(
  'atlas_play_ranker',
  'Play ranking folded into atlas-trade signal scoring system',
  'atlas-trade',
  ARRAY['RANK_PLAYS', 'PLAY_RANKER', 'SCORE_PLAYS'],
  'Play ranking now part of atlas-trade signal-to-decision priority queue'
),
(
  'atlas_play_tracker',
  'Play tracking merged into atlas_trade_audit immutable log',
  'atlas-trade',
  ARRAY['TRACK_PLAY', 'PLAY_TRACKER', 'UPDATE_PLAY'],
  'All trade tracking now recorded in atlas_trade_audit with signed_hash integrity'
),
(
  'atlas_regime_detector',
  'Regime detection folded into atlas-trade context layer',
  'atlas-trade',
  ARRAY['DETECT_REGIME', 'REGIME_DETECTOR', 'MARKET_REGIME'],
  'Regime state now stored as regime_at_entry in atlas_trade_audit per trade'
),
(
  'atlas_opportunity_scan',
  'Replaced by unified atlas-trade opportunity scanner covering all asset classes',
  'atlas-trade',
  ARRAY['OPPORTUNITY_SCAN', 'SCAN_OPPORTUNITIES', 'FIND_OPPORTUNITIES'],
  'Cross-asset opportunity scanning now the primary atlas-trade action'
),
(
  'atlas_counterfactual',
  'Counterfactual analysis merged into atlas-trade post-trade evaluation',
  'atlas-trade',
  ARRAY['COUNTERFACTUAL', 'WHAT_IF', 'BACKTEST_DECISION'],
  'Counterfactual outcomes now recorded in atlas_trade_audit outcome jsonb field'
),
(
  'atlas_news_scan',
  'News scanning consolidated into atlas-trade signal intelligence pipeline',
  'atlas-trade',
  ARRAY['NEWS_SCAN', 'SCAN_NEWS', 'NEWS_BRIEF'],
  'News signals now feed directly into atlas-trade opportunity and risk assessment'
),
(
  'get_live_prices',
  'Price fetching internalized into atlas-trade data layer',
  'atlas-trade',
  ARRAY['GET_PRICES', 'LIVE_PRICES', 'FETCH_QUOTES'],
  'Price data now fetched inline by atlas-trade with rate limiting and caching'
);

-- ─── atlas-re (5 functions) ───────────────────────────────────────────────────

INSERT INTO public.deprecation_log (deprecated_name, reason, absorbed_into, original_actions, notes) VALUES
(
  'atlas_re_brief',
  'Real estate brief consolidated into atlas-re portfolio summary',
  'atlas-re',
  ARRAY['RE_BRIEF', 'REALESTATE_BRIEF', 'PROPERTY_SUMMARY'],
  'RE briefing now generated on demand by atlas-re with full portfolio context'
),
(
  'atlas_deal_scan',
  'Deal scanning merged into atlas-re acquisition pipeline',
  'atlas-re',
  ARRAY['DEAL_SCAN', 'SCAN_DEALS', 'FIND_DEALS'],
  'Deal discovery now part of atlas-re scouting cycle with auto-underwrite trigger'
),
(
  'atlas_deal_underwrite',
  'Underwriting folded into atlas-re evaluation stage',
  'atlas-re',
  ARRAY['UNDERWRITE', 'DEAL_UNDERWRITE', 'EVALUATE_DEAL'],
  'Underwriting logic now runs automatically when atlas-re deal advances to EVALUATION stage'
),
(
  'atlas_lease_monitor',
  'Lease monitoring merged into atlas-re property management layer',
  'atlas-re',
  ARRAY['LEASE_MONITOR', 'MONITOR_LEASES', 'CHECK_LEASES'],
  'Lease expiry and renewal alerts now generated by atlas-re weekly cron'
),
(
  'atlas_re_risk_check',
  'RE risk check consolidated into atlas-re decision gate',
  'atlas-re',
  ARRAY['RE_RISK_CHECK', 'REALESTATE_RISK', 'PROPERTY_RISK'],
  'RE risk assessment now embedded in atlas-re YELLOW/RED decision routing'
);

-- ─── atlas-portfolio (6 functions) ────────────────────────────────────────────

INSERT INTO public.deprecation_log (deprecated_name, reason, absorbed_into, original_actions, notes) VALUES
(
  'atlas_portfolio_sync',
  'Portfolio sync replaced by atlas_portfolio_state table with trigger-based rebalancing',
  'atlas-portfolio',
  ARRAY['PORTFOLIO_SYNC', 'SYNC_PORTFOLIO', 'REFRESH_PORTFOLIO'],
  'Portfolio state now maintained in atlas_portfolio_state with automatic rebalancing detection'
),
(
  'atlas_allocate_capital',
  'Capital allocation folded into atlas-portfolio rebalancing engine',
  'atlas-portfolio',
  ARRAY['ALLOCATE_CAPITAL', 'CAPITAL_ALLOCATION', 'REBALANCE'],
  'Allocation decisions now flow through atlas_decision_queue as YELLOW decisions'
),
(
  'atlas_balance_sheet',
  'Balance sheet replaced by unified atlas_portfolio_state with linked balance_sheet_snapshots',
  'atlas-portfolio',
  ARRAY['BALANCE_SHEET', 'NET_WORTH', 'PORTFOLIO_SUMMARY'],
  'Balance sheet now computed from atlas_portfolio_state aggregating all verticals'
),
(
  'atlas_expense_audit',
  'Expense auditing merged into atlas-portfolio income velocity monitoring',
  'atlas-portfolio',
  ARRAY['EXPENSE_AUDIT', 'AUDIT_EXPENSES', 'REVIEW_SPENDING'],
  'Expense analysis now part of atlas-portfolio monthly cashflow monitoring'
),
(
  'atlas_income_velocity',
  'Income velocity tracking consolidated into atlas-portfolio state monitoring',
  'atlas-portfolio',
  ARRAY['INCOME_VELOCITY', 'CASHFLOW_VELOCITY', 'REVENUE_RATE'],
  'Income velocity now tracked via monthly_cashflow field in atlas_portfolio_state'
),
(
  'calculate_operator_trajectory',
  'Multi-operator trajectory calculation deprecated with multi-operator architecture',
  'atlas-portfolio',
  ARRAY['OPERATOR_TRAJECTORY', 'CALCULATE_TRAJECTORY', 'PROJECT_PERFORMANCE'],
  'DEPRECATED: old multi-operator concept. Portfolio trajectory now computed for single operator via atlas-portfolio annual_return_rate'
);

-- ─── atlas-signal (3 functions) ───────────────────────────────────────────────

INSERT INTO public.deprecation_log (deprecated_name, reason, absorbed_into, original_actions, notes) VALUES
(
  'forge_morning_engine',
  'Morning engine replaced by atlas-signal structured morning brief',
  'atlas-signal',
  ARRAY['MORNING_ENGINE', 'RUN_MORNING', 'MORNING_CYCLE'],
  'Morning signal now generated by atlas-signal and published to atlas_report_archive'
),
(
  'forge_weekly_review',
  'Weekly review folded into atlas-signal weekly digest cycle',
  'atlas-signal',
  ARRAY['WEEKLY_REVIEW', 'WEEK_IN_REVIEW', 'WEEKLY_SUMMARY'],
  'Weekly review now part of atlas-signal report generation on Sunday cron'
),
(
  'forge_alerts',
  'Alert system replaced by atlas_alerts table with atlas_decision_queue integration',
  'atlas-signal',
  ARRAY['SEND_ALERT', 'FORGE_ALERT', 'TRIGGER_ALERT'],
  'Alerts now written to atlas_alerts table and routed by decision type (RED triggers immediate notification)'
);

-- ─── atlas-business (4 functions) ─────────────────────────────────────────────

INSERT INTO public.deprecation_log (deprecated_name, reason, absorbed_into, original_actions, notes) VALUES
(
  'atlas_business_brief',
  'Business brief consolidated into atlas-business pipeline summary',
  'atlas-business',
  ARRAY['BUSINESS_BRIEF', 'PIPELINE_BRIEF', 'BUSINESS_SUMMARY'],
  'Business briefing now generated by atlas-business from atlas_business_pipeline state'
),
(
  'atlas_business_risk_check',
  'Business risk check merged into atlas-business evaluation gate',
  'atlas-business',
  ARRAY['BUSINESS_RISK_CHECK', 'RISK_CHECK_BUSINESS', 'VENTURE_RISK'],
  'Business risk now assessed during EVALUATION stage with YELLOW/RED decision routing'
),
(
  'atlas_pipeline_scout',
  'Pipeline scouting replaced by atlas-business autonomous SCOUTING stage',
  'atlas-business',
  ARRAY['PIPELINE_SCOUT', 'SCOUT_PIPELINE', 'FIND_BUSINESSES'],
  'Scouting now runs on atlas-business cron every 2 days with execution_compatibility_score filter'
),
(
  'atlas_send_outreach',
  'Outreach consolidated into atlas-business contractor and client communication layer',
  'atlas-business',
  ARRAY['SEND_OUTREACH', 'OUTREACH', 'CONTACT_PROSPECT'],
  'All outreach now routes through atlas_decision_queue as ORANGE decision requiring approval'
);

-- ─── DEPRECATED (no successor) ────────────────────────────────────────────────

INSERT INTO public.deprecation_log (deprecated_name, reason, absorbed_into, original_actions, notes) VALUES
(
  'atlas_obsidian_sync',
  'Obsidian filesystem MCP removed from new architecture; knowledge management internalized',
  'DEPRECATED',
  ARRAY['OBSIDIAN_SYNC', 'SYNC_OBSIDIAN', 'WRITE_VAULT'],
  'Obsidian filesystem MCP not in new architecture. Research and memory now stored in atlas_memory and atlas_dossier_full tables. No successor function.'
);
