// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hycpzeskartlkybsfkbh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5Y3B6ZXNrYXJ0bGt5YnNma2JoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkwMTg5NDQsImV4cCI6MjA5NDU5NDk0NH0.rGORUni_oc-1v5AZCGq35G8sahKOXVqa4NlzYtghYYw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
